---
- name: Playbook Mattw 2023
  hosts: all
  become: true

  vars_files:
    - vars.yml

  pre_tasks:
    - name: Check SSH connectivity and ping
      ping:

    - name: Update apt cache
      apt:
        update_cache: yes

  tasks:
    
    - name: Git Installation
      include_role:
        name: git
      
    - name: Install Docker and Docker-compose
      include_role:
        name: docker

    - name: Run docker compose
      include_role:
        name: docker-compose
