apiVersion: apps/v1

kind: Deployment
metadata:
  name: yolo-client-deployment
spec:
  selector:
    matchLabels:
      app: yolo-client
  template:
    metadata:
      labels:
        app: yolo-client
    spec:
      containers:
      - name: yolo-client
        image: mattwanjau/yolo-client:v2.0.0
        env:
          - name: PORT
            value: "3000"
             
        ports:
        - containerPort: 3000
