---
  - name: install docker
    apt:
      name:
        - docker.io
      update_cache: yes

  - name: install python package manager
    apt:
      name: python3-pip

  - name: install sdk python
    pip:
      name:
        - docker
        - docker-compose